// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dailyTasks.Persistence;

namespace dailyTasks.Migrations
{
    [DbContext(typeof(DailyTasksDbContext))]
    partial class DailyTasksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("dailyTasks.Models.DailyTasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DailyTasks");
                });

            modelBuilder.Entity("dailyTasks.Models.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyTasksId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DailyTasksId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("dailyTasks.Models.Tasks", b =>
                {
                    b.HasOne("dailyTasks.Models.DailyTasks", null)
                        .WithMany("Tasks")
                        .HasForeignKey("DailyTasksId");
                });
#pragma warning restore 612, 618
        }
    }
}
